# Generated by Django 2.0.2 on 2018-03-18 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180317_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='modified_name',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
